# Generated by Django 5.0.7 on 2024-08-20 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='billing_address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_address',
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('CE', 'Pago contra entrega'), ('PT', 'Pago en tienda'), ('PSE', 'PSE')], max_length=3),
        ),
        migrations.DeleteModel(
            name='Address',
        ),
    ]
