# Generated by Django 5.0.7 on 2024-08-20 01:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_order_billing_address_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locality', models.CharField(choices=[('USA', 'Usaquen'), ('CHA', 'Chapinero'), ('STF', 'Santa Fe'), ('SCR', 'San Cristobal'), ('USM', 'Usme'), ('TUN', 'Tunjuelito'), ('BOS', 'Bosa'), ('KEN', 'Kennedy'), ('FON', 'Fontibon'), ('ENG', 'Engativa'), ('SUB', 'Suba'), ('BAU', 'Barrios Unidos'), ('TEU', 'Teusaquillo'), ('MAR', 'Los Martires'), ('ANT', 'Antonio Nariño'), ('PUE', 'Puente Aranda'), ('CAN', 'Candelaria'), ('RUR', 'Rafael Uribe'), ('CBO', 'Ciudad Bolivar'), ('SUM', 'Sumapaz')], max_length=3)),
                ('street_type', models.CharField(choices=[('CL', 'Calle'), ('CRA', 'Carrera'), ('AV', 'Avenida'), ('ACR', 'Avenida Carrera'), ('ACL', 'Avenida Calle'), ('DG', 'Diagonal'), ('TV', 'Transversal'), ('AUT', 'Autopista'), ('VIA', 'Via'), ('CIR', 'Circular'), ('CVC', 'Circunvalar'), ('MZ', 'Manzana')], max_length=3)),
                ('street_value', models.CharField(max_length=255)),
                ('number', models.CharField(max_length=255)),
                ('complement', models.CharField(max_length=255)),
                ('address_type', models.CharField(choices=[('B', 'Billing'), ('S', 'Shipping')], max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='billing_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_address', to='orders.address'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipping_address', to='orders.address'),
        ),
    ]
