# Generated by Django 5.0.7 on 2024-09-01 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_address_email_address_first_name_address_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
