# Generated by Django 5.0.7 on 2024-09-03 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_remove_orderitem_coupon_order_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='shipping_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('P', 'Pendiente'), ('A', 'Aceptado'), ('R', 'Rechazado'), ('D', 'Entregado')], max_length=1),
        ),
    ]
