# Generated by Django 5.0.7 on 2025-11-23 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_payment_shipping_cost_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='locality',
            field=models.CharField(choices=[('USA', 'Usaquen'), ('CHA', 'Chapinero'), ('STF', 'Santa Fe'), ('SC', 'San Cristobal'), ('USM', 'Usme'), ('TUN', 'Tunjuelito'), ('BOS', 'Bosa'), ('KEN', 'Kennedy'), ('FON', 'Fontibon'), ('ENG', 'Engativa'), ('SUB', 'Suba'), ('BAU', 'Barrios Unidos'), ('TEU', 'Teusaquillo'), ('MAR', 'Los Martires'), ('ANT', 'Antonio Nariño'), ('PUE', 'Pueblo Aranda'), ('CAN', 'Candelaria'), ('RUR', 'Rafael Uribe'), ('CBO', 'Ciudad Bolivar'), ('SUM', 'Sumapaz')], max_length=3),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('P', 'Pendiente'), ('C', 'Completado'), ('F', 'Fallido')], max_length=1),
        ),
    ]
