# Generated by Django 5.0.7 on 2024-08-08 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_product_until_discount_alter_productimage_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='until_discount',
            new_name='discount_end_date',
        ),
    ]
